# core encoder/decoder sizes
num_encoder_layers_ts:      2
hidden_size_ts:            32
num_decoder_layers:        2
decoder_output_dim:        16
temporal_width_future:     8
temporal_hidden_size_future: 16
temporal_decoder_hidden:   16
use_layer_norm:            false
dropout:                   0.1

# image-encoder backbone
image_backbone:           "tf_efficientnetv2_b0.in1k"
image_pretrained:         true

classification: false