_target_: pytorch_lightning.Trainer

# Trainer args
max_epochs:        100
gpus:              1
precision:         16
log_every_n_steps: 10

# optional PL logger settings
default_root_dir: lightning_logs
