# config/datamodule/solar.yaml
_target_: timage_forecasting.datamodule.TimeSeriesWithImageDataModule

# ── DataModule-only parameters ────────────────────────────────────────────────
# (these get consumed by the DataModule itself, not forwarded to TimeSeriesDataSet)
df_path:      "experiments/task5/train_processed_img_task5.csv"
test_df_path: "experiments/task5/test_processed_img_task5.csv"
keep_ids: [0, 1]
parse_dates:
  - date

val_split:   0.2
batch_size:  32
num_workers: 4

# ── TimeSeriesWithImageDataSet parameters ────────────────────────────────────
# (these will be passed as **ts_kwargs to the DataModule and then into
#  TimeSeriesDataSet via **base in setup())
time_idx:                  "time_idx"
target:                    "kwh"
group_ids:
  - panel_id

static_reals:              []
static_categoricals:
  - solar_term
  - hod
  - dow
  - moy

time_varying_known_reals:   []
time_varying_unknown_reals:
  - kwh
time_varying_known_categoricals:   []
time_varying_unknown_categoricals: []

image_cols_start: "sat_v1"
image_cols_end: "sat_v576"
image_shape: [1, 24, 24]

max_encoder_length:  168   # one week of hourly history
max_prediction_length: 24    # next 24 h
