version_base: 1.1
hydra:
  run:
    dir: .
  output_subdir: .

defaults:
  - _self_
  - dataset: solar
  - model: timage
  - trainer: default

experiment:
  seed: 42
  cutoff: 0.2
  batch_size: 64
  num_worker: 4
